swagger: '2.0'
info:
  version: 1.0.0
  title: COAX BOOTCAMP

tags:
- name: search
  description: finds books
- name: auth
  description: authorization and registration
- name: favorite
  description: favorite books
- name: readlater
  description: read later list
- name: functionals
  description: social functions
# schemes:
# - http
paths:
  /search:
    get:
      tags:
      - search
      summary: finds books
      produces:
      - application/json
      parameters:
      - in: query
        type: string
        name: search
        description: my query request where search - books and page - number of page request
        required: true
      responses:
        200:
          description: OK
        404:
          description: Not Found
  /book/:id:
    get:
      tags:
      - search
      summary: find one book by atribyte
      produces:
      - application/json
      parameters:
      - in: query
        type: string
        name: isbn13
        description: isbn13 - personal book atribute
      responses:
        200:
          description: OK
        404:
          description: Not Found
  /auth/login:
    post:
      tags:
      - auth
      summary: authorization
      consumes:
      - application/json
      produces:
      - application/json
      description: in body you need to write email and pass
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /auth/register:
    post:
      tags:
      - auth
      summary: registration
      consumes:
      - application/json
      produces:
      - application/json
      description: in body you need to write name, email and pass 
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /favorite:
    get:
      tags:
      - favorite
      summary: show favorite page
      produces:
      - application/json
      description: you must be login to see the data
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /favorite/add:
    post:
      tags:
      - favorite
      summary: add book to favorite page
      description: in the body of the request indicate the article isbn13 and you must be login
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /favorite/remove:
    post:
      tags:
      - favorite
      summary: remove book from favorite page
      description: in the body of the request indicate the book id from db and you must be login
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /readlater:
    get:
      tags:
      - readlater
      summary: show readlater page
      produces:
      - application/json
      description: you must be login to see the data
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /readlater/add:
    post:
      tags:
      - readlater
      summary: add book to readlater page
      description: in the body of the request indicate the article-isbn13, bookName - bookName, and you must be login
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /readlater/remove:
    post:
      tags:
      - readlater
      summary: remove book from favorite page
      description: in the body of the request indicate the book id from db and you must be login
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /func/addComment:
    post:
      tags:
      - functionals
      summary: add comment to book
      description: in the body of the request indicate the article-isbn13, body of comment - textarea, if there is a file - data,type of data image|audio|video, time, client id - author  and you must be login
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        403:
          description: Forbidden
  /func/deleteComment:
    post:
      tags:
      - functionals
      summary: remove comment
      description: in the body of the request indicate the book id - bookid and you must be login
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        406:
          description: Not Acceptable
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
# definitions:
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /butenko/bootcamp/1.0.0
schemes:
 - https
 - http